apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: react-app-service
spec:
  hosts:
  - reactprod.virtualtechbox.com
  gateways:
  - istio-ingressgateway
  http:
  - name: "react-app-service"
    retries:
      attempts: 5
      perTryTimeout: 600s
    route:
    - destination:
        host: react-app-service.reactprod.svc.cluster.local
        port:
          number: 80